version: "1.1.1"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama_server
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama/models  # Persist model files

  backend:
    build: .
    container_name: content_moderator_backend
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["/bin/bash", "/app/backend/start.sh"]

  frontend:
    build: .
    container_name: content_moderator_frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: ["/bin/bash", "/app/frontend/start_frontend.sh"]
